permutive.settings:
  type: config_object
  label: 'Permutive configuration'
  mapping:
    project_id:
      type: string
      label: 'Your project id'
    api_key:
      type: string
      label: 'Your API key'
